USE [master]
GO

/****** Object:  Database [Лобанов_Продажи]    Script Date: 08.09.2022 19:54:08 ******/
CREATE DATABASE [Лобанов_Продажи]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Лобанов_Продажи', FILENAME = N'D:\Soft\Microsoft SQL Server 2019 Express\MSSQL15.SQLEXPRESS\MSSQL\DATA\Лобанов_Продажи.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Лобанов_Продажи_log', FILENAME = N'D:\Soft\Microsoft SQL Server 2019 Express\MSSQL15.SQLEXPRESS\MSSQL\DATA\Лобанов_Продажи_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Лобанов_Продажи].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Лобанов_Продажи] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET ARITHABORT OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Лобанов_Продажи] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Лобанов_Продажи] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Лобанов_Продажи] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Лобанов_Продажи] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Лобанов_Продажи] SET  MULTI_USER 
GO

ALTER DATABASE [Лобанов_Продажи] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Лобанов_Продажи] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Лобанов_Продажи] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Лобанов_Продажи] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Лобанов_Продажи] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Лобанов_Продажи] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Лобанов_Продажи] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Лобанов_Продажи] SET  READ_WRITE 
GO

