SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
From AUDITORIUM_TYPE Inner Join AUDITORIUM
On AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%Компьютер%'