SELECT PULPIT.PULPIT_NAME as Кафедра,
isnull(TEACHER.TEACHER_NAME, '***') as Преподаватель
FROM PULPIT FULL Outer Join TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT
WHERE TEACHER.TEACHER_NAME is null

SELECT isnull(PULPIT.PULPIT_NAME, '***') as Кафедра,
TEACHER.TEACHER_NAME as Преподаватель
FROM TEACHER Right Outer Join PULPIT
ON TEACHER.PULPIT = PULPIT.PULPIT
WHERE PULPIT.PULPIT_NAME is null

SELECT PULPIT.PULPIT_NAME as Кафедра,
TEACHER.TEACHER_NAME as Преподаватель
FROM PULPIT FULL Outer Join TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT
WHERE TEACHER.TEACHER_NAME is not null AND PULPIT.PULPIT_NAME is not null